/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pds;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Wrath
 */
public class Order extends javax.swing.JPanel {
    MainForm mainform;
    JDialog parenta;
    OrderItems list = new OrderItems();
    int totalc = 0;
    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        String[] mod = new String[OrderItems.items.length];
        for(int i=0; i < OrderItems.items.length; i++){
            mod[i] = OrderItems.items[i].name;
        }
        jComboPiz.setModel(new javax.swing.DefaultComboBoxModel(mod));
        jComboPizItemStateChanged(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboSize = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboPiz = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextQuan = new javax.swing.JSpinner();

        jLabel4.setText("Rs. 0");

        jComboSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large" }));
        jComboSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboSizeItemStateChanged(evt);
            }
        });
        jComboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSizeActionPerformed(evt);
            }
        });

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboPiz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Margherita", "Mexican Wave", "Italian Treat", "Chilly Slice" }));
        jComboPiz.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboPizItemStateChanged(evt);
            }
        });
        jComboPiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPizActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Size", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Cost :");

        jLabel2.setText("Rs. 0");

        jLabel3.setText("Pizza :");

        jLabel5.setText("Size :");

        jLabel6.setText("Cost :");

        jTextQuan.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboPiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextQuan)))
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboPiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (((int)jTextQuan.getValue())==0) javax.swing.JOptionPane.showMessageDialog(null,"Enter Quantity");
        System.out.println(OrderItems.items[jComboPiz.getSelectedIndex()].sizeable? jComboSize.getSelectedIndex():0);
        list.quant[jComboPiz.getSelectedIndex()][(OrderItems.items[jComboPiz.getSelectedIndex()].sizeable)? jComboSize.getSelectedIndex():0]+= (int)(jTextQuan.getValue());
        updateOrderList();
        //((javax.swing.table.DefaultTableModel)jTable1.getModel()).addRow(new Object[]{jTable1.getRowCount(),jComboPiz.getSelectedItem(),jComboSize.getSelectedItem(),jTextQuan.getText()}) ;       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void updateOrderList(){
        int c = ((javax.swing.table.DefaultTableModel)jTable1.getModel()).getRowCount();
        for(int i = c-1;  i>=0;i--)
        ((javax.swing.table.DefaultTableModel)jTable1.getModel()).removeRow(i);
        int totalc=0;
        for(int i = 0; i<OrderItems.items.length;i++)
        {
            for(int j = 0 ; j<3;j++) {
                if(list.quant[i][j] == 0) continue;
                String df = ((OrderItems.items[i].sizeable)?(new String[]{"Small","Medium","Large"}[j]):("-"));
                float f =1.0f;
                if (OrderItems.items[i].sizeable) 
                    f += (j -1) * (0.3f); 
                Object s[] = {OrderItems.items[i].name,df,list.quant[i][j],(int)(OrderItems.items[i].cost * f) * list.quant[i][j]};
                totalc += (int)(OrderItems.items[i].cost * f) * list.quant[i][j];
                
                ((javax.swing.table.DefaultTableModel)jTable1.getModel()).addRow(s) ;       // TODO add your handling code here:
                
            }
        }
        jLabel2.setText("Rs. " + totalc);
    }
    private void jComboPizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPizActionPerformed

    private void jComboPizItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboPizItemStateChanged
        // TODO add your handling code here:
        Item it = OrderItems.items[jComboPiz.getSelectedIndex()];
        if (it.sizeable) jComboSize.setEnabled(true); else jComboSize.setEnabled(false);
        float f =1.0f;
        if (it.sizeable) f += (jComboSize.getSelectedIndex() -1) * (0.3f);
        jLabel4.setText("Rs. " + (int)(it.cost * f));
        
    }//GEN-LAST:event_jComboPizItemStateChanged

    private void jComboSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboSizeItemStateChanged
        jComboPizItemStateChanged(null);// TODO add your handling code here:
    }//GEN-LAST:event_jComboSizeItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Container s =this.parenta;
        
        s.remove(this);
        Customer c = new Customer();
        c.order = this;
        s.add(c);
        
        //System.out.println(c.isVisible());
        s.setVisible(false);
        //try{Thread.sleep(2000);}catch(Throwable e){}
        s.setVisible(true);
        /*if (true) return;
        JDialog sg = new JDialog( (JDialog)this.getParent(),true);
        sg.setBounds(100,100,500,400);
        
        System.out.println("STart");
                sg.setVisible(true);
                System.out.println("ENd");
        sg.add(new Order());
        javax.swing.JOptionPane.showMessageDialog(null,sg.getComponents()[0].isVisible());

        
        try{Thread.sleep(2000);}catch(Throwable e){}*/
        //sg.add(new Customer());
        //sg.add(new Order());
        //add(new Customer());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSizeActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboPiz;
    private javax.swing.JComboBox jComboSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner jTextQuan;
    // End of variables declaration//GEN-END:variables
}
